name: basic_layout_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/pic1.jpeg
  - assets/pic2.jpeg
  - assets/pic3.jpeg
  - assets/pavlova.jpeg
  - assets/materialApps.png
  - assets/yunika.png